### ISSUE TITLE
 The documentation page is not available

### ISSUE THREAD

**Issue by sodrooome** [vintasoftware/drf-rw-serializers#11]
* drf-rw-serializers version: 1.01
* Django version: 2.2
* Python version: 3.7
* Operating System: Windows 10 64-bit (Build 17763)

### Description

- the documentation pages is not available when i tried to open it
- when I want to try the demo via `example_app` an error appears such as `500 internal server error`
- also, I have migrated the `example_app` but I am still instructed to migrate again

Any suggest or idea to help with this? Thanks before

**Comment by hugobessa** [comment]
The documentation is available here @sodrooome [https://drf-rw-serializers.readthedocs.io/en/latest/](https://drf-rw-serializers.readthedocs.io/en/latest/). 

Did you add the example_app to you own project, right? Can you send me the stack trace?
