### ISSUE TITLE
Added support for Django 2.2

### ISSUE THREAD

**Issue by repodevs** [vintasoftware/drf-rw-serializers#14]
* drf-rw-serializers version: 1.0.1
* Django version: 2.2
* Python version: 3.6
* Operating System: Mac OS 10.14

### Description

When support for Django 2.2 released?

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by moliholy** [comment]
I just added https://github.com/vintasoftware/drf-rw-serializers/pull/16 to include support for django 2.2. There are no significant differences between 2.1 and 2.2, and also 2.2 is LTS, meaning that it's important to support it.
