### ISSUE TITLE
Remove `<3.1` requirement

### ISSUE THREAD

**Issue by filipeximenes** [vintasoftware/drf-rw-serializers#32]
* drf-rw-serializers version: latest
* Django version: --
* Python version: --
* Operating System: --

### Description

I think there's not much gain in pinning an upper version requirement for Django specially since it's a minor version. I think we should either remove the upper limit or make it `<4.0`

### What I Did

----

**Comment by borisko123** [comment]
hello, what are your plans about remove restrictions for django 4?
