### ISSUE TITLE
License inconsistency

### ISSUE THREAD

**Issue by lunkwill42** [vintasoftware/drf-rw-serializers#47]
* drf-rw-serializers version: master

### Description

The contents of `LICENSE.txt` and `setup.py` are not in agreement about which license this project is released under.

`LICENSE.txt` contains the **MIT license** text, while the Trove classifiers in `setup.py` (which are used to tag/classify the package on PyPI) claims the license is **AGPL 3.0**. These licenses are not compatible - it would be prudent to resolve this, as many projects would avoid dependencies that are licensed with AGPL.

**Comment by snosratiershad** [comment]
MIT License is compatible with AGPL, but not in the other way.
As I discovered, there is no copyright or license notice that claims rights on AGPLv3 on drf-rw-serializers, but MIT license contains it's own, so everyone should use it under the terms of MIT license.
but about the PyPi classifiers I think it's a mistake, as the license parameter of setup metadata is exactly on MIT (setup.py:52) so I'm going to fix classifier in a PR.

Request for comments, Thanks @lunkwill42.
