### ISSUE TITLE
version 1.0.5 not available on pypi.org

### ISSUE THREAD

**Issue by soile1991** [vintasoftware/drf-rw-serializers#49]
Hello in the documentation site it states that there is a version 1.0.5 that supports Django 4 but it's not available on pypi.org. Can you please release it?

Thank you

**Comment by yawei-workmate** [comment]
Hi Team, please release the latest 1.0.5 for Django 4 support, thanks

**Comment by rvlb** [comment]
Hi folks, we've now released version 1.0.5 on pypi https://pypi.org/project/drf-rw-serializers/1.0.5/
