### ISSUE TITLE
New version 1.2.0 require to upgrade djangorestframework

### ISSUE THREAD

**Issue by sshishov** [vintasoftware/drf-rw-serializers#84]
* drf-rw-serializers version: move from 1.1.1 to 1.2.0
* Django version: 4.2.13
* Python version: 3.11.9
* Operating System: Linux

### Description

When we are trying to update the dependency (dependabot), it is failing because it wants to update `djangorestframework==3.15.1` as well. We are not upgrading as we have some breaking changes there.

There is no indication that exactly this version is required and before there were no issues. I guess the setup with poetry brings something...

### What I Did

As `drf-rw-serializers` does not depend on specific version of DRF, installation of new version of the library should not try to update DRF version.

NOTE: we are using `ruff's` UV, but I guess it should not be the reason...

```
(venv) server@ad9c683d6e80:~/app$ uv pip freeze | grep -E "(drf-rw-serializers=|djangorestframework=)"
djangorestframework==3.14.0
drf-rw-serializers==1.1.1

(venv) server@ad9c683d6e80:~/app$ uv pip install drf_rw_serializers==1.2.0
Resolved 5 packages in 322ms
Installed 2 packages in 22ms
 - djangorestframework==3.14.0
 + djangorestframework==3.15.1
 - drf-rw-serializers==1.1.1
 + drf-rw-serializers==1.2.0

(venv) server@ad9c683d6e80:~/app$ uv pip freeze | grep -E "(drf-rw-serializers=|djangorestframework=)"
djangorestframework==3.15.1
drf-rw-serializers==1.2.0
```

**Comment by fjsj** [comment]
Thanks for the report. We'll check what we can do.

**Comment by fjsj** [comment]
@pamella could you please check if it's safe to support an older version of DRF?

**Comment by pamella** [comment]
Hello @sshishov, we have restored support for `djangorestframework 3.14.0` in the latest release `1.3.0`. Could you upgrade `drf-rw-serializers` to `1.3.0` and let us know how it goes? Thanks!

**Comment by sshishov** [comment]
Hello @pamella , I can confirm that the library now is installable now under DRF `3.14.x`, but please note that I did not want to specify exact version, I just wanted to point out that before there was no "pin" for DRF and not it has appeared along with "upgrade required".

You can close this, but if someone will create similar issue from `3.13.x` then probably you should loosen the requirements properly.

Thanks. Working for me as expected.

**Comment by pamella** [comment]
@sshishov  Nice, glad that `3.14.x` is working.  

Yes, I see, that's because we dropped the support for `3.13.x` and below.
